"""add role to users

Revision ID: 3934ec94995b
Revises: 9dc19239e7c0
Create Date: 2026-04-15 20:36:45.014842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3934ec94995b'
down_revision: Union[str, Sequence[str], None] = '9dc19239e7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'role')
    # ### end Alembic commands ###
