"""add user_id to tasks

Revision ID: 9dc19239e7c0
Revises: 
Create Date: 2026-04-14 23:29:54.443563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dc19239e7c0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks_table', 'user_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_table', type_='foreignkey')
    op.drop_column('tasks_table', 'user_id')
    # ### end Alembic commands ###
